name: comfy

# Single docker-compose.yml for both local and TrueNAS Dockge
# Use environment variables to configure deployment-specific settings

services:
  comfy:
    image: ghcr.io/pixeloven/comfyui-docker/complete:cuda-latest
    container_name: comfy
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${COMFY_DATA_PATH:-./data}:/data:delegated
    stop_signal: SIGKILL
    tty: true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comfy.entrypoints=web"
      - "traefik.http.services.comfy.loadbalancer.server.port=8188"
      - "traefik.http.routers.comfy.service=comfy"
      - "traefik.http.routers.comfy.rule=Host(`comfy.docker.localhost`)"
      # - "traefik.http.routers.comfy.tls=true"
      # - "traefik.http.routers.comfy.tls.certresolver=letencrypt"
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${GPU_DRIVER:-nvidia}
              count: ${GPU_COUNT:-all}
              capabilities: 
                - ${GPU_CAPABILITIES:-gpu}

networks:
  proxy:
    name: proxy
    external: true
