name: comfyui

services:

  comfy-nvidia:
    image: ghcr.io/pixeloven/comfyui-docker/comfy-nvidia:latest
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - ./extra_model_paths.yaml:/home/ubuntu/app/extra_model_paths.yaml:ro,cached
      - ./data:/data:delegated
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.comfyui.rule=Host(`comfyui.local.briangebel.com`)"
        - "traefik.http.routers.comfyui.entrypoints=websecure"
        - "traefik.http.services.comfyui.loadbalancer.server.port=8188"
        - "traefik.http.routers.comfyui.service=comfyui"
        - "traefik.http.routers.comfyui.tls.certresolver=leresolver"
        - "traefik.http.middlewares.comfyui-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.comfyui-headers.headers.customrequestheaders.X-Forwarded-Host=comfyui.local.briangebel.com"
    networks:
      - comfyui_network

networks:
  comfyui_network:
    name: comfyui_network
    driver: bridge


