name: comfy

# Single docker-compose.yml for both local and TrueNAS Dockge
# Use environment variables to configure deployment-specific settings

services:
  comfy:
    image: ghcr.io/pixeloven/comfyui-docker/${COMFY_IMAGE:-complete:cuda-latest}
    container_name: comfy
    user: ${PUID:-1000}:${PGID:-1000}
    runtime: nvidia
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=8188
      - CLI_ARGS=--enable-cors-header
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${COMFY_CUSTOM_NODE_PATH:-./data/custom_nodes}:/app/custom_nodes:rw
      - ${COMFY_INPUT_PATH:-./data/input}:/app/input:rw
      - ${COMFY_MODEL_PATH:-./data/models}:/app/models:ro
      - ${COMFY_OUTPUT_PATH:-./data/output}:/app/output:rw
      - ${COMFY_TEMP_PATH:-./data/temp}:/app/temp:rw
      - ${COMFY_USER_PATH:-./data/user}:/app/user:rw
    # stop_signal: SIGKILL
    # tty: true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comfy.entrypoints=websecure"
      - "traefik.http.services.comfy.loadbalancer.server.port=8188"
      - "traefik.http.routers.comfy.service=comfy"
      - "traefik.http.routers.comfy.rule=Host(`comfy.${HOSTNAME:-pixeloven.com}`)"
      - "traefik.http.routers.comfy.tls=true"
      - "traefik.http.routers.comfy.tls.certresolver=letsencrypt"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  data:
