services:
  # Expand to support the other ui - update traefic for comfyui
  # Setup other swarm setups the same - create none swarm support as well?

  download:
    image: comfy-download
    # user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=
    networks:
      - stable_diffusion_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data

  comfyui:
    image: comfy-ui
    # user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CLI_ARGS=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
      - ./output:/output
    stop_signal: SIGKILL
    networks:
      - proxy
      - stable_diffusion_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.stable-diffusion.rule=Host(`stable-diffusion.local.briangebel.com`)"
        # - "traefik.http.routers.stable-diffusion.rule=Path(`/service/stable-diffusion`)"
        - "traefik.http.routers.stable-diffusion.entrypoints=websecure"
        - "traefik.http.services.stable-diffusion.loadbalancer.server.port=7860"
        - "traefik.http.routers.stable-diffusion.service=stable-diffusion"
        - "traefik.http.routers.stable-diffusion.tls.certresolver=leresolver"

networks:
  proxy:
    external: true
  stable_diffusion_network:
    name: stable_diffusion_network
    driver: overlay
    attachable: true
