services:

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    hostname: '{{.Node.Hostname}}'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./storage:/storage
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - proxy
      - syncthing_network
    restart: unless-stopped
    deploy:
      labels:
            
        # Web Interface Support
        - "traefik.enable=true"
        - "traefik.http.routers.syncthing.rule=Host(`syncthing.local.briangebel.com`)"
        - "traefik.http.routers.syncthing.entrypoints=websecure"
        - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
        - "traefik.http.routers.syncthing.service=syncthing"
        - "traefik.http.routers.syncthing.tls.certresolver=leresolver"

networks:
  proxy:
    external: true
  syncthing_network:
    name: syncthing_network
    driver: overlay
    attachable: true