name: traefik

services:
  
  # https://doc.traefik.io/traefik/v1.4/user-guide/examples/#lets-encrypt-support
  # https://www.reddit.com/r/portainer/comments/12z8ctr/how_to_setup_traefik_to_access_containers_in/
  # Setup .env for portable configuration 

  traefik:
    container_name: traefik
    image: "traefik:v3.5"
    command: --configfile=/traefik.yml
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro # Traefik config file
      - traefik-certs:/certs # Docker volume to store the acme file for the Certificates
      #- /var/log:/var/log
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.local.briangebel.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      # - "traefik.http.routers.traefik.middlewares=redirect-to-https"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH:-test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/}"
    networks:
      - proxy

  whoami:
    image: "traefik/whoami"
    container_name: "traefik-whoami"
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.whoami.rule=Host(`whoami.local.briangebel.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
# docker network create proxy
# @todo: network should come up before traefik is started
# @todo invoke and comfy should share the same models
# @todo move data and output outside of the services path

volumes:
  traefik-certs:
    name: traefik-certs