services:
  
  # https://doc.traefik.io/traefik/v1.4/user-guide/examples/#lets-encrypt-support
  # https://www.reddit.com/r/portainer/comments/12z8ctr/how_to_setup_traefik_to_access_containers_in/
  # Setup .env for portable configuration 

  # Consider Swarm? https://github.com/bluepuma77/traefik-best-practice/tree/main/docker-swarm-traefik

  traefik:
    container_name: traefik
    image: "traefik:v3.3"
    command:
      - "--log.level=${LOG_LEVEL:-DEBUG}"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.leresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=brian@pixeloven.com" #Set your email address here, is for the generation of SSL certificates with Let's Encrypt. 
      - "--certificatesresolvers.leresolver.acme.storage=./acme.json"
      - "--certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  whoami:
    image: "traefik/whoami"
    container_name: "traefik-whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local.briangebel.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
