name: invokeai
# Any leasons we can learn from InvokeAI?
# https://github.com/invoke-ai/InvokeAI/blob/main/docker/docker-compose.yml
# @todo need to test this out and the swarm (rename all the swarm to stack? seems standard)
# @todo comfyui and invoke should share directory structure for outputs and models
services:
  invokeai:
    image: ghcr.io/invoke-ai/invokeai:latest
    container_name: invokeai
    environment:
      - INVOKEAI_ROOT=/workspace
      - INVOKEAI_HOST=0.0.0.0
      - INVOKEAI_PORT=9090
    volumes:
      - ./models:/workspace/models
      - ./outputs:/workspace/outputs
      - ./configs:/workspace/configs
      - ./databases:/workspace/databases
    ports:
      - "9090:9090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.invokeai.rule=Host(`invokeai.local.briangebel.com`)"
      - "traefik.http.routers.invokeai.entrypoints=websecure"
      - "traefik.http.services.invokeai.loabalancer.server.port=9090"
      - "traefik.http.routers.invokeai.service=invokeai"
      - "traefik.http.routers.invokeai.tls.certresolver=leresolver"
      - "traefik.http.routers.invokeai.middlewares=invokeai-headers"
      - "traefik.http.middlewares.invokeai-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.invokeai-headers.headers.customrequestheaders.X-Forwarded-Host=invokeai.local.briangebel.com"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [compute, utility]
    networks:
      - proxy
      - invokeai_network

networks:
  proxy:
    external: true
    name: proxy
  invokeai_network:
    name: invokeai_network
    driver: bridge